FROM golang:1.18 AS building

COPY . /building
WORKDIR /building

RUN make frpc

FROM alpine:3

COPY --from=building /building/bin/frpc /usr/bin/frpc
ADD run.sh /root/run.sh
RUN chmod +x /root/run.sh
CMD /root/run.sh